// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AcknowledgeConnectionApiV1SessionsSessionIdConnectionsAttemptIdAckPostData, AcknowledgeConnectionApiV1SessionsSessionIdConnectionsAttemptIdAckPostErrors, AcknowledgeConnectionApiV1SessionsSessionIdConnectionsAttemptIdAckPostResponses, CreateLanguageProfileApiV1LanguageProfilesPostData, CreateLanguageProfileApiV1LanguageProfilesPostErrors, CreateLanguageProfileApiV1LanguageProfilesPostResponses, CreateSessionApiV1SessionsPostData, CreateSessionApiV1SessionsPostErrors, CreateSessionApiV1SessionsPostResponses, EndSessionApiV1SessionsSessionIdEndPostData, EndSessionApiV1SessionsSessionIdEndPostErrors, EndSessionApiV1SessionsSessionIdEndPostResponses, ExchangeWebrtcApiV1SessionsSessionIdWebrtcPostData, ExchangeWebrtcApiV1SessionsSessionIdWebrtcPostErrors, ExchangeWebrtcApiV1SessionsSessionIdWebrtcPostResponses, GetLanguagePairsApiV1LanguagePairsGetData, GetLanguagePairsApiV1LanguagePairsGetErrors, GetLanguagePairsApiV1LanguagePairsGetResponses, GetMeApiV1MeGetData, GetMeApiV1MeGetErrors, GetMeApiV1MeGetResponses, GetSessionApiV1SessionsSessionIdGetData, GetSessionApiV1SessionsSessionIdGetErrors, GetSessionApiV1SessionsSessionIdGetResponses, HealthHealthGetData, HealthHealthGetResponses, LogoutAuthLogoutPostData, LogoutAuthLogoutPostErrors, LogoutAuthLogoutPostResponses, ReadyReadyGetData, ReadyReadyGetResponses, UpdatePreferencesApiV1MePreferencesPatchData, UpdatePreferencesApiV1MePreferencesPatchErrors, UpdatePreferencesApiV1MePreferencesPatchResponses, VoiceAvailabilityApiV1SessionsAvailabilityGetData, VoiceAvailabilityApiV1SessionsAvailabilityGetErrors, VoiceAvailabilityApiV1SessionsAvailabilityGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Language Pairs
 */
export const getLanguagePairsApiV1LanguagePairsGet = <ThrowOnError extends boolean = false>(options?: Options<GetLanguagePairsApiV1LanguagePairsGetData, ThrowOnError>) => (options?.client ?? client).get<GetLanguagePairsApiV1LanguagePairsGetResponses, GetLanguagePairsApiV1LanguagePairsGetErrors, ThrowOnError>({ url: '/api/v1/language-pairs', ...options });

/**
 * Create Language Profile
 */
export const createLanguageProfileApiV1LanguageProfilesPost = <ThrowOnError extends boolean = false>(options: Options<CreateLanguageProfileApiV1LanguageProfilesPostData, ThrowOnError>) => (options.client ?? client).post<CreateLanguageProfileApiV1LanguageProfilesPostResponses, CreateLanguageProfileApiV1LanguageProfilesPostErrors, ThrowOnError>({
    url: '/api/v1/language-profiles',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Me
 */
export const getMeApiV1MeGet = <ThrowOnError extends boolean = false>(options?: Options<GetMeApiV1MeGetData, ThrowOnError>) => (options?.client ?? client).get<GetMeApiV1MeGetResponses, GetMeApiV1MeGetErrors, ThrowOnError>({ url: '/api/v1/me', ...options });

/**
 * Update Preferences
 */
export const updatePreferencesApiV1MePreferencesPatch = <ThrowOnError extends boolean = false>(options: Options<UpdatePreferencesApiV1MePreferencesPatchData, ThrowOnError>) => (options.client ?? client).patch<UpdatePreferencesApiV1MePreferencesPatchResponses, UpdatePreferencesApiV1MePreferencesPatchErrors, ThrowOnError>({
    url: '/api/v1/me/preferences',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create Session
 */
export const createSessionApiV1SessionsPost = <ThrowOnError extends boolean = false>(options: Options<CreateSessionApiV1SessionsPostData, ThrowOnError>) => (options.client ?? client).post<CreateSessionApiV1SessionsPostResponses, CreateSessionApiV1SessionsPostErrors, ThrowOnError>({
    url: '/api/v1/sessions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Voice Availability
 */
export const voiceAvailabilityApiV1SessionsAvailabilityGet = <ThrowOnError extends boolean = false>(options?: Options<VoiceAvailabilityApiV1SessionsAvailabilityGetData, ThrowOnError>) => (options?.client ?? client).get<VoiceAvailabilityApiV1SessionsAvailabilityGetResponses, VoiceAvailabilityApiV1SessionsAvailabilityGetErrors, ThrowOnError>({ url: '/api/v1/sessions/availability', ...options });

/**
 * Get Session
 */
export const getSessionApiV1SessionsSessionIdGet = <ThrowOnError extends boolean = false>(options: Options<GetSessionApiV1SessionsSessionIdGetData, ThrowOnError>) => (options.client ?? client).get<GetSessionApiV1SessionsSessionIdGetResponses, GetSessionApiV1SessionsSessionIdGetErrors, ThrowOnError>({ url: '/api/v1/sessions/{session_id}', ...options });

/**
 * Acknowledge Connection
 */
export const acknowledgeConnectionApiV1SessionsSessionIdConnectionsAttemptIdAckPost = <ThrowOnError extends boolean = false>(options: Options<AcknowledgeConnectionApiV1SessionsSessionIdConnectionsAttemptIdAckPostData, ThrowOnError>) => (options.client ?? client).post<AcknowledgeConnectionApiV1SessionsSessionIdConnectionsAttemptIdAckPostResponses, AcknowledgeConnectionApiV1SessionsSessionIdConnectionsAttemptIdAckPostErrors, ThrowOnError>({ url: '/api/v1/sessions/{session_id}/connections/{attempt_id}/ack', ...options });

/**
 * End Session
 */
export const endSessionApiV1SessionsSessionIdEndPost = <ThrowOnError extends boolean = false>(options: Options<EndSessionApiV1SessionsSessionIdEndPostData, ThrowOnError>) => (options.client ?? client).post<EndSessionApiV1SessionsSessionIdEndPostResponses, EndSessionApiV1SessionsSessionIdEndPostErrors, ThrowOnError>({ url: '/api/v1/sessions/{session_id}/end', ...options });

/**
 * Exchange Webrtc
 */
export const exchangeWebrtcApiV1SessionsSessionIdWebrtcPost = <ThrowOnError extends boolean = false>(options: Options<ExchangeWebrtcApiV1SessionsSessionIdWebrtcPostData, ThrowOnError>) => (options.client ?? client).post<ExchangeWebrtcApiV1SessionsSessionIdWebrtcPostResponses, ExchangeWebrtcApiV1SessionsSessionIdWebrtcPostErrors, ThrowOnError>({ url: '/api/v1/sessions/{session_id}/webrtc', ...options });

/**
 * Logout
 */
export const logoutAuthLogoutPost = <ThrowOnError extends boolean = false>(options: Options<LogoutAuthLogoutPostData, ThrowOnError>) => (options.client ?? client).post<LogoutAuthLogoutPostResponses, LogoutAuthLogoutPostErrors, ThrowOnError>({ url: '/auth/logout', ...options });

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Ready
 */
export const readyReadyGet = <ThrowOnError extends boolean = false>(options?: Options<ReadyReadyGetData, ThrowOnError>) => (options?.client ?? client).get<ReadyReadyGetResponses, unknown, ThrowOnError>({ url: '/ready', ...options });
