// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ApiErrorDetails
 */
export type ApiErrorDetails = {
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Requestid
     */
    requestId: string;
};

/**
 * ApiErrorResponse
 */
export type ApiErrorResponse = {
    error: ApiErrorDetails;
};

/**
 * CorrectionPreference
 */
export type CorrectionPreference = 'light' | 'balanced' | 'frequent';

/**
 * CreateSessionRequest
 */
export type CreateSessionRequest = {
    /**
     * Languageprofileid
     */
    languageProfileId: string;
};

/**
 * LanguageProfileResponse
 */
export type LanguageProfileResponse = {
    /**
     * Baselanguageid
     */
    baseLanguageId: string;
    /**
     * Id
     */
    id: string;
    status: LanguageProfileStatus;
    /**
     * Targetlanguageid
     */
    targetLanguageId: string;
};

/**
 * LanguageProfileStatus
 */
export type LanguageProfileStatus = 'active' | 'archived';

/**
 * MeResponse
 */
export type MeResponse = {
    activeLanguageProfile: LanguageProfileResponse;
    /**
     * Csrftoken
     */
    csrfToken: string;
    onboarding: OnboardingResponse;
    preferences: PreferencesResponse;
    user: UserResponse;
};

/**
 * OnboardingResponse
 */
export type OnboardingResponse = {
    /**
     * Complete
     */
    complete: boolean;
};

/**
 * PreferencePatch
 */
export type PreferencePatch = {
    /**
     * Captionsenabled
     */
    captionsEnabled?: boolean;
    /**
     * Correctionpreference
     */
    correctionPreference?: CorrectionPreference;
    /**
     * Timezone
     */
    timezone?: string;
    /**
     * Tutorpace
     */
    tutorPace?: TutorPace;
};

/**
 * PreferencesResponse
 */
export type PreferencesResponse = {
    /**
     * Captionsenabled
     */
    captionsEnabled: boolean;
    correctionPreference: CorrectionPreference;
    /**
     * Timezone
     */
    timezone: string;
    tutorPace: TutorPace;
    /**
     * Version
     */
    version: number;
};

/**
 * SessionResponse
 */
export type SessionResponse = {
    /**
     * Connectedlimitms
     */
    connectedLimitMs: number;
    /**
     * Connectedms
     */
    connectedMs: number;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Id
     */
    id: string;
    /**
     * Objective
     */
    objective: string;
    /**
     * Reservationexpiresat
     */
    reservationExpiresAt: string;
    /**
     * Rowversion
     */
    rowVersion: number;
    /**
     * State
     */
    state: string;
};

/**
 * TutorPace
 */
export type TutorPace = 'level' | 'gentle' | 'steady' | 'natural';

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Displayname
     */
    displayName: string;
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
    status: UserStatus;
};

/**
 * UserStatus
 */
export type UserStatus = 'active' | 'suspended' | 'deletion_pending';

export type GetMeApiV1MeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type GetMeApiV1MeGetErrors = {
    /**
     * Mori error envelope
     */
    default: ApiErrorResponse;
};

export type GetMeApiV1MeGetError = GetMeApiV1MeGetErrors[keyof GetMeApiV1MeGetErrors];

export type GetMeApiV1MeGetResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type GetMeApiV1MeGetResponse = GetMeApiV1MeGetResponses[keyof GetMeApiV1MeGetResponses];

export type UpdatePreferencesApiV1MePreferencesPatchData = {
    body: PreferencePatch;
    headers: {
        'X-CSRF-Token': string;
        'If-Match': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/me/preferences';
};

export type UpdatePreferencesApiV1MePreferencesPatchErrors = {
    /**
     * Mori error envelope
     */
    default: ApiErrorResponse;
};

export type UpdatePreferencesApiV1MePreferencesPatchError = UpdatePreferencesApiV1MePreferencesPatchErrors[keyof UpdatePreferencesApiV1MePreferencesPatchErrors];

export type UpdatePreferencesApiV1MePreferencesPatchResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type UpdatePreferencesApiV1MePreferencesPatchResponse = UpdatePreferencesApiV1MePreferencesPatchResponses[keyof UpdatePreferencesApiV1MePreferencesPatchResponses];

export type CreateSessionApiV1SessionsPostData = {
    body: CreateSessionRequest;
    headers: {
        'X-CSRF-Token': string;
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/sessions';
};

export type CreateSessionApiV1SessionsPostErrors = {
    /**
     * Mori error envelope
     */
    default: ApiErrorResponse;
};

export type CreateSessionApiV1SessionsPostError = CreateSessionApiV1SessionsPostErrors[keyof CreateSessionApiV1SessionsPostErrors];

export type CreateSessionApiV1SessionsPostResponses = {
    /**
     * Successful Response
     */
    200: SessionResponse;
};

export type CreateSessionApiV1SessionsPostResponse = CreateSessionApiV1SessionsPostResponses[keyof CreateSessionApiV1SessionsPostResponses];

export type GetSessionApiV1SessionsSessionIdGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{session_id}';
};

export type GetSessionApiV1SessionsSessionIdGetErrors = {
    /**
     * Mori error envelope
     */
    default: ApiErrorResponse;
};

export type GetSessionApiV1SessionsSessionIdGetError = GetSessionApiV1SessionsSessionIdGetErrors[keyof GetSessionApiV1SessionsSessionIdGetErrors];

export type GetSessionApiV1SessionsSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: SessionResponse;
};

export type GetSessionApiV1SessionsSessionIdGetResponse = GetSessionApiV1SessionsSessionIdGetResponses[keyof GetSessionApiV1SessionsSessionIdGetResponses];

export type LogoutAuthLogoutPostData = {
    body?: never;
    headers: {
        'X-CSRF-Token': string;
    };
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutAuthLogoutPostErrors = {
    /**
     * Mori error envelope
     */
    default: ApiErrorResponse;
};

export type LogoutAuthLogoutPostError = LogoutAuthLogoutPostErrors[keyof LogoutAuthLogoutPostErrors];

export type LogoutAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutAuthLogoutPostResponse = LogoutAuthLogoutPostResponses[keyof LogoutAuthLogoutPostResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type ReadyReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ready';
};

export type ReadyReadyGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
