// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ApiErrorDetails
 */
export type ApiErrorDetails = {
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Requestid
     */
    requestId: string;
};

/**
 * ApiErrorResponse
 */
export type ApiErrorResponse = {
    error: ApiErrorDetails;
};

/**
 * CorrectionPreference
 */
export type CorrectionPreference = 'light' | 'balanced' | 'frequent';

/**
 * CreateProfileRequest
 */
export type CreateProfileRequest = {
    /**
     * Baselanguageid
     */
    baseLanguageId: string;
    correctionPreference?: CorrectionPreference;
    /**
     * Interests
     */
    interests?: Array<string>;
    startingChoice: StartingChoice;
    /**
     * Targetlanguageid
     */
    targetLanguageId: string;
    /**
     * Timezone
     */
    timezone?: string;
    tutorPace?: TutorPace;
};

/**
 * CreateSessionRequest
 */
export type CreateSessionRequest = {
    /**
     * Languageprofileid
     */
    languageProfileId: string;
    /**
     * Requestedwords
     */
    requestedWords?: Array<string>;
    /**
     * Topic
     */
    topic?: string | null;
};

/**
 * LanguagePairResponse
 */
export type LanguagePairResponse = {
    /**
     * Available
     */
    available: boolean;
    /**
     * Baselanguageid
     */
    baseLanguageId: string;
    /**
     * Baselanguagename
     */
    baseLanguageName: string;
    /**
     * Targetlanguageid
     */
    targetLanguageId: string;
    /**
     * Targetlanguagename
     */
    targetLanguageName: string;
    /**
     * Targetnativename
     */
    targetNativeName: string;
};

/**
 * LanguagePairsResponse
 */
export type LanguagePairsResponse = {
    /**
     * Pairs
     */
    pairs: Array<LanguagePairResponse>;
};

/**
 * LanguageProfileResponse
 */
export type LanguageProfileResponse = {
    /**
     * Baselanguageid
     */
    baseLanguageId: string;
    /**
     * Id
     */
    id: string;
    /**
     * Languageselectionconfirmed
     */
    languageSelectionConfirmed: boolean;
    learning: LearningSettingsResponse;
    status: LanguageProfileStatus;
    /**
     * Targetlanguageid
     */
    targetLanguageId: string;
    /**
     * Version
     */
    version: number;
};

/**
 * LanguageProfileStatus
 */
export type LanguageProfileStatus = 'active' | 'archived';

/**
 * LearningMode
 */
export type LearningMode = 'learning' | 'practice';

/**
 * LearningSettingsResponse
 */
export type LearningSettingsResponse = {
    mode: LearningMode;
    provisionalLevel: StartingChoice | null;
    startingChoice: StartingChoice;
    /**
     * Version
     */
    version: number;
};

/**
 * MeResponse
 */
export type MeResponse = {
    activeLanguageProfile: LanguageProfileResponse | null;
    /**
     * Csrftoken
     */
    csrfToken: string;
    onboarding: OnboardingResponse;
    preferences: PreferencesResponse | null;
    user: UserResponse;
    /**
     * Version
     */
    version: number;
};

/**
 * OnboardingResponse
 */
export type OnboardingResponse = {
    /**
     * Complete
     */
    complete: boolean;
};

/**
 * PlanPreviewResponse
 */
export type PlanPreviewResponse = {
    /**
     * Objectives
     */
    objectives: Array<string>;
};

/**
 * PreferencePatch
 */
export type PreferencePatch = {
    /**
     * Captionsenabled
     */
    captionsEnabled?: boolean;
    /**
     * Correctionpreference
     */
    correctionPreference?: CorrectionPreference;
    /**
     * Timezone
     */
    timezone?: string;
    /**
     * Tutorpace
     */
    tutorPace?: TutorPace;
};

/**
 * PreferencesResponse
 */
export type PreferencesResponse = {
    /**
     * Captionsenabled
     */
    captionsEnabled: boolean;
    correctionPreference: CorrectionPreference;
    /**
     * Interests
     */
    interests: Array<string>;
    /**
     * Timezone
     */
    timezone: string;
    tutorPace: TutorPace;
    /**
     * Version
     */
    version: number;
};

/**
 * SessionResponse
 */
export type SessionResponse = {
    /**
     * Connectedlimitms
     */
    connectedLimitMs: number;
    /**
     * Connectedms
     */
    connectedMs: number;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Id
     */
    id: string;
    /**
     * Mode
     */
    mode: string;
    /**
     * Objective
     */
    objective: string;
    planPreview: PlanPreviewResponse;
    /**
     * Reservationexpiresat
     */
    reservationExpiresAt: string;
    /**
     * Rowversion
     */
    rowVersion: number;
    /**
     * State
     */
    state: string;
};

/**
 * StartingChoice
 */
export type StartingChoice = 'beginner' | 'intermediate' | 'advanced' | 'fluent' | 'unsure';

/**
 * TutorPace
 */
export type TutorPace = 'level' | 'gentle' | 'steady' | 'natural';

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Displayname
     */
    displayName: string;
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
    status: UserStatus;
};

/**
 * UserStatus
 */
export type UserStatus = 'active' | 'suspended' | 'deletion_pending';

/**
 * VoiceAvailabilityResponse
 */
export type VoiceAvailabilityResponse = {
    /**
     * Available
     */
    available: boolean;
    /**
     * Maxcallseconds
     */
    maxCallSeconds: number;
};

export type GetLanguagePairsApiV1LanguagePairsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/language-pairs';
};

export type GetLanguagePairsApiV1LanguagePairsGetErrors = {
    /**
     * Mori error envelope
     */
    default: ApiErrorResponse;
};

export type GetLanguagePairsApiV1LanguagePairsGetError = GetLanguagePairsApiV1LanguagePairsGetErrors[keyof GetLanguagePairsApiV1LanguagePairsGetErrors];

export type GetLanguagePairsApiV1LanguagePairsGetResponses = {
    /**
     * Successful Response
     */
    200: LanguagePairsResponse;
};

export type GetLanguagePairsApiV1LanguagePairsGetResponse = GetLanguagePairsApiV1LanguagePairsGetResponses[keyof GetLanguagePairsApiV1LanguagePairsGetResponses];

export type CreateLanguageProfileApiV1LanguageProfilesPostData = {
    body: CreateProfileRequest;
    headers: {
        'X-CSRF-Token': string;
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/language-profiles';
};

export type CreateLanguageProfileApiV1LanguageProfilesPostErrors = {
    /**
     * Mori error envelope
     */
    default: ApiErrorResponse;
};

export type CreateLanguageProfileApiV1LanguageProfilesPostError = CreateLanguageProfileApiV1LanguageProfilesPostErrors[keyof CreateLanguageProfileApiV1LanguageProfilesPostErrors];

export type CreateLanguageProfileApiV1LanguageProfilesPostResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type CreateLanguageProfileApiV1LanguageProfilesPostResponse = CreateLanguageProfileApiV1LanguageProfilesPostResponses[keyof CreateLanguageProfileApiV1LanguageProfilesPostResponses];

export type GetMeApiV1MeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type GetMeApiV1MeGetErrors = {
    /**
     * Mori error envelope
     */
    default: ApiErrorResponse;
};

export type GetMeApiV1MeGetError = GetMeApiV1MeGetErrors[keyof GetMeApiV1MeGetErrors];

export type GetMeApiV1MeGetResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type GetMeApiV1MeGetResponse = GetMeApiV1MeGetResponses[keyof GetMeApiV1MeGetResponses];

export type UpdatePreferencesApiV1MePreferencesPatchData = {
    body: PreferencePatch;
    headers: {
        'X-CSRF-Token': string;
        'If-Match': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/me/preferences';
};

export type UpdatePreferencesApiV1MePreferencesPatchErrors = {
    /**
     * Mori error envelope
     */
    default: ApiErrorResponse;
};

export type UpdatePreferencesApiV1MePreferencesPatchError = UpdatePreferencesApiV1MePreferencesPatchErrors[keyof UpdatePreferencesApiV1MePreferencesPatchErrors];

export type UpdatePreferencesApiV1MePreferencesPatchResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type UpdatePreferencesApiV1MePreferencesPatchResponse = UpdatePreferencesApiV1MePreferencesPatchResponses[keyof UpdatePreferencesApiV1MePreferencesPatchResponses];

export type CreateSessionApiV1SessionsPostData = {
    body: CreateSessionRequest;
    headers: {
        'X-CSRF-Token': string;
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/sessions';
};

export type CreateSessionApiV1SessionsPostErrors = {
    /**
     * Mori error envelope
     */
    default: ApiErrorResponse;
};

export type CreateSessionApiV1SessionsPostError = CreateSessionApiV1SessionsPostErrors[keyof CreateSessionApiV1SessionsPostErrors];

export type CreateSessionApiV1SessionsPostResponses = {
    /**
     * Successful Response
     */
    200: SessionResponse;
};

export type CreateSessionApiV1SessionsPostResponse = CreateSessionApiV1SessionsPostResponses[keyof CreateSessionApiV1SessionsPostResponses];

export type VoiceAvailabilityApiV1SessionsAvailabilityGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/sessions/availability';
};

export type VoiceAvailabilityApiV1SessionsAvailabilityGetErrors = {
    /**
     * Mori error envelope
     */
    default: ApiErrorResponse;
};

export type VoiceAvailabilityApiV1SessionsAvailabilityGetError = VoiceAvailabilityApiV1SessionsAvailabilityGetErrors[keyof VoiceAvailabilityApiV1SessionsAvailabilityGetErrors];

export type VoiceAvailabilityApiV1SessionsAvailabilityGetResponses = {
    /**
     * Successful Response
     */
    200: VoiceAvailabilityResponse;
};

export type VoiceAvailabilityApiV1SessionsAvailabilityGetResponse = VoiceAvailabilityApiV1SessionsAvailabilityGetResponses[keyof VoiceAvailabilityApiV1SessionsAvailabilityGetResponses];

export type GetSessionApiV1SessionsSessionIdGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{session_id}';
};

export type GetSessionApiV1SessionsSessionIdGetErrors = {
    /**
     * Mori error envelope
     */
    default: ApiErrorResponse;
};

export type GetSessionApiV1SessionsSessionIdGetError = GetSessionApiV1SessionsSessionIdGetErrors[keyof GetSessionApiV1SessionsSessionIdGetErrors];

export type GetSessionApiV1SessionsSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: SessionResponse;
};

export type GetSessionApiV1SessionsSessionIdGetResponse = GetSessionApiV1SessionsSessionIdGetResponses[keyof GetSessionApiV1SessionsSessionIdGetResponses];

export type AcknowledgeConnectionApiV1SessionsSessionIdConnectionsAttemptIdAckPostData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
        /**
         * Attempt Id
         */
        attempt_id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{session_id}/connections/{attempt_id}/ack';
};

export type AcknowledgeConnectionApiV1SessionsSessionIdConnectionsAttemptIdAckPostErrors = {
    /**
     * Mori error envelope
     */
    default: ApiErrorResponse;
};

export type AcknowledgeConnectionApiV1SessionsSessionIdConnectionsAttemptIdAckPostError = AcknowledgeConnectionApiV1SessionsSessionIdConnectionsAttemptIdAckPostErrors[keyof AcknowledgeConnectionApiV1SessionsSessionIdConnectionsAttemptIdAckPostErrors];

export type AcknowledgeConnectionApiV1SessionsSessionIdConnectionsAttemptIdAckPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AcknowledgeConnectionApiV1SessionsSessionIdConnectionsAttemptIdAckPostResponse = AcknowledgeConnectionApiV1SessionsSessionIdConnectionsAttemptIdAckPostResponses[keyof AcknowledgeConnectionApiV1SessionsSessionIdConnectionsAttemptIdAckPostResponses];

export type EndSessionApiV1SessionsSessionIdEndPostData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{session_id}/end';
};

export type EndSessionApiV1SessionsSessionIdEndPostErrors = {
    /**
     * Mori error envelope
     */
    default: ApiErrorResponse;
};

export type EndSessionApiV1SessionsSessionIdEndPostError = EndSessionApiV1SessionsSessionIdEndPostErrors[keyof EndSessionApiV1SessionsSessionIdEndPostErrors];

export type EndSessionApiV1SessionsSessionIdEndPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type EndSessionApiV1SessionsSessionIdEndPostResponse = EndSessionApiV1SessionsSessionIdEndPostResponses[keyof EndSessionApiV1SessionsSessionIdEndPostResponses];

export type ExchangeWebrtcApiV1SessionsSessionIdWebrtcPostData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/sessions/{session_id}/webrtc';
};

export type ExchangeWebrtcApiV1SessionsSessionIdWebrtcPostErrors = {
    /**
     * Mori error envelope
     */
    default: ApiErrorResponse;
};

export type ExchangeWebrtcApiV1SessionsSessionIdWebrtcPostError = ExchangeWebrtcApiV1SessionsSessionIdWebrtcPostErrors[keyof ExchangeWebrtcApiV1SessionsSessionIdWebrtcPostErrors];

export type ExchangeWebrtcApiV1SessionsSessionIdWebrtcPostResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type ExchangeWebrtcApiV1SessionsSessionIdWebrtcPostResponse = ExchangeWebrtcApiV1SessionsSessionIdWebrtcPostResponses[keyof ExchangeWebrtcApiV1SessionsSessionIdWebrtcPostResponses];

export type LogoutAuthLogoutPostData = {
    body?: never;
    headers: {
        'X-CSRF-Token': string;
    };
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutAuthLogoutPostErrors = {
    /**
     * Mori error envelope
     */
    default: ApiErrorResponse;
};

export type LogoutAuthLogoutPostError = LogoutAuthLogoutPostErrors[keyof LogoutAuthLogoutPostErrors];

export type LogoutAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutAuthLogoutPostResponse = LogoutAuthLogoutPostResponses[keyof LogoutAuthLogoutPostResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type ReadyReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ready';
};

export type ReadyReadyGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
