// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * ApiErrorDetails
 */
export const zApiErrorDetails = z.object({
    code: z.string(),
    message: z.string(),
    requestId: z.string()
});

/**
 * ApiErrorResponse
 */
export const zApiErrorResponse = z.object({
    error: zApiErrorDetails
});

/**
 * CorrectionPreference
 */
export const zCorrectionPreference = z.enum([
    'light',
    'balanced',
    'frequent'
]);

/**
 * CreateSessionRequest
 */
export const zCreateSessionRequest = z.object({
    languageProfileId: z.uuid(),
    requestedWords: z.array(z.string().min(1).max(48)).max(8).optional().default([]),
    topic: z.string().max(160).nullish()
});

/**
 * LanguagePairResponse
 */
export const zLanguagePairResponse = z.object({
    available: z.boolean(),
    baseLanguageId: z.string(),
    baseLanguageName: z.string(),
    targetLanguageId: z.string(),
    targetLanguageName: z.string(),
    targetNativeName: z.string()
});

/**
 * LanguagePairsResponse
 */
export const zLanguagePairsResponse = z.object({
    pairs: z.array(zLanguagePairResponse)
});

/**
 * LanguageProfileStatus
 */
export const zLanguageProfileStatus = z.enum(['active', 'archived']);

/**
 * LearningMode
 */
export const zLearningMode = z.enum(['learning', 'practice']);

/**
 * OnboardingResponse
 */
export const zOnboardingResponse = z.object({
    complete: z.boolean()
});

/**
 * PlanPreviewResponse
 */
export const zPlanPreviewResponse = z.object({
    objectives: z.array(z.string())
});

/**
 * SessionResponse
 */
export const zSessionResponse = z.object({
    connectedLimitMs: z.int(),
    connectedMs: z.int(),
    createdAt: z.iso.datetime(),
    id: z.uuid(),
    mode: z.string(),
    objective: z.string(),
    planPreview: zPlanPreviewResponse,
    reservationExpiresAt: z.iso.datetime(),
    rowVersion: z.int(),
    state: z.string()
});

/**
 * StartingChoice
 */
export const zStartingChoice = z.enum([
    'beginner',
    'intermediate',
    'advanced',
    'fluent',
    'unsure'
]);

/**
 * LearningSettingsResponse
 */
export const zLearningSettingsResponse = z.object({
    mode: zLearningMode,
    provisionalLevel: zStartingChoice.nullable(),
    startingChoice: zStartingChoice,
    version: z.int().gt(0)
});

/**
 * LanguageProfileResponse
 */
export const zLanguageProfileResponse = z.object({
    baseLanguageId: z.string(),
    id: z.uuid(),
    languageSelectionConfirmed: z.boolean(),
    learning: zLearningSettingsResponse,
    status: zLanguageProfileStatus,
    targetLanguageId: z.string(),
    version: z.int().gt(0)
});

/**
 * TutorPace
 */
export const zTutorPace = z.enum([
    'level',
    'gentle',
    'steady',
    'natural'
]);

/**
 * CreateProfileRequest
 */
export const zCreateProfileRequest = z.object({
    baseLanguageId: z.string().min(1).max(32),
    correctionPreference: zCorrectionPreference.optional().default('balanced'),
    interests: z.array(z.string()).optional(),
    startingChoice: zStartingChoice,
    targetLanguageId: z.string().min(1).max(32),
    timezone: z.string().min(1).max(64).optional().default('UTC'),
    tutorPace: zTutorPace.optional().default('level')
});

/**
 * PreferencePatch
 */
export const zPreferencePatch = z.object({
    captionsEnabled: z.boolean().optional(),
    correctionPreference: zCorrectionPreference.optional(),
    timezone: z.string().min(1).max(64).optional(),
    tutorPace: zTutorPace.optional()
});

/**
 * PreferencesResponse
 */
export const zPreferencesResponse = z.object({
    captionsEnabled: z.boolean(),
    correctionPreference: zCorrectionPreference,
    interests: z.array(z.string()),
    timezone: z.string().min(1),
    tutorPace: zTutorPace,
    version: z.int().gt(0)
});

/**
 * UserStatus
 */
export const zUserStatus = z.enum([
    'active',
    'suspended',
    'deletion_pending'
]);

/**
 * UserResponse
 */
export const zUserResponse = z.object({
    displayName: z.string().min(1),
    email: z.email(),
    id: z.uuid(),
    status: zUserStatus
});

/**
 * MeResponse
 */
export const zMeResponse = z.object({
    activeLanguageProfile: zLanguageProfileResponse.nullable(),
    csrfToken: z.string().min(1),
    onboarding: zOnboardingResponse,
    preferences: zPreferencesResponse.nullable(),
    user: zUserResponse,
    version: z.int().gt(0)
});

/**
 * Successful Response
 */
export const zGetLanguagePairsApiV1LanguagePairsGetResponse = zLanguagePairsResponse;

export const zCreateLanguageProfileApiV1LanguageProfilesPostBody = zCreateProfileRequest;

export const zCreateLanguageProfileApiV1LanguageProfilesPostHeaders = z.object({
    'X-CSRF-Token': z.string(),
    'Idempotency-Key': z.string()
});

/**
 * Successful Response
 */
export const zCreateLanguageProfileApiV1LanguageProfilesPostResponse = zMeResponse;

/**
 * Successful Response
 */
export const zGetMeApiV1MeGetResponse = zMeResponse;

export const zUpdatePreferencesApiV1MePreferencesPatchBody = zPreferencePatch;

export const zUpdatePreferencesApiV1MePreferencesPatchHeaders = z.object({
    'X-CSRF-Token': z.string(),
    'If-Match': z.string()
});

/**
 * Successful Response
 */
export const zUpdatePreferencesApiV1MePreferencesPatchResponse = zMeResponse;

export const zCreateSessionApiV1SessionsPostBody = zCreateSessionRequest;

export const zCreateSessionApiV1SessionsPostHeaders = z.object({
    'X-CSRF-Token': z.string(),
    'Idempotency-Key': z.string()
});

/**
 * Successful Response
 */
export const zCreateSessionApiV1SessionsPostResponse = zSessionResponse;

export const zGetSessionApiV1SessionsSessionIdGetPath = z.object({
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetSessionApiV1SessionsSessionIdGetResponse = zSessionResponse;

export const zLogoutAuthLogoutPostHeaders = z.object({
    'X-CSRF-Token': z.string()
});

/**
 * Successful Response
 */
export const zLogoutAuthLogoutPostResponse = z.void();

/**
 * Response Health Health Get
 *
 * Successful Response
 */
export const zHealthHealthGetResponse = z.record(z.string(), z.string());
